### ISSUE TITLE
I am getting this error after a while while running your application.

### ISSUE THREAD

**Issue by inohtech** [OgarPlus/Ogar-Plus-GUI#1]
Ogar-Plus ~ A modified Ogar Server
[Ogar-Plus] Loaded stats server on port 88
[Ogar-Plus] Listening on port 666
[Ogar-Plus] Current game mode is Experimental
[Ogar-Plus] Remote GUI Authecation Key : ####
>[Ogar-Plus] Remote GUI connected!
[Ogar-Plus] Remote GUI address : ###.###.#.###:56676
[Ogar-Plus] Removed 1 cells
[Ogar-Plus] Successfully changed leaderboard values
[Ogar-Plus] Added 3 player bots
[Ogar-Plus] Added 1 player bots
[Ogar-Plus] Changed game mode to Virus Off
[Ogar-Plus] Changed game mode to AirDrop
[Ogar-Plus] Changed game mode to AirDrop
[Ogar-Plus] Changed game mode to Zombie FFA
[Ogar-Plus] Changed game mode to Zombie Team
TypeError: Cannot read property 'indexOf' of undefined
    at Cell.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+U+s+e+r+s+\+F+u+j+i+t+s+u+\+D+o+c+
u+m+e+n+t+s+\+G+i+t+H+u+b+\+O+g+a+r+-+P+l+u+s+\+s+r+c+\+g+a+m+e+m+o+d+e+s+\+E+x+
p+e+r+i+m+e+n+t+a+l+.+j+s.MotherCell.onRemove (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+U+s+e+r+s+\+F+u+j+i+t+s+u+\+
D+o+c+u+m+e+n+t+s+\+G+i+t+H+u+b+\+O+g+a+r+-+P+l+u+s+\+s+r+c+\+G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.removeNode (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+U+s+e+r+s+\+F+u+j+i+t+s+u+\+
D+o+c+u+m+e+n+t+s+\+G+i+t+H+u+b+\+O+g+a+r+-+P+l+u+s+\+s+r+c+\+G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.updateMoveEngine (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+U+s+e+r+s+\+F+u+j+i+t+s+u+\+
D+o+c+u+m+e+n+t+s+\+G+i+t+H+u+b+\+O+g+a+r+-+P+l+u+s+\+s+r+c+\+G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.cellTick (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+U+s+e+r+s+\+F+u+j+i+t+s+u+\+
D+o+c+u+m+e+n+t+s+\+G+i+t+H+u+b+\+O+g+a+r+-+P+l+u+s+\+s+r+c+\+G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.mainLoop (<anonymous>)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by Porama6400** [comment]
It's because Experimental gamemode

if you change to other gamemode after playing experimental , some of mother cell will not remove properly
if you eat it , server will crash like that

**Comment by Porama6400** [comment]
we'll talk about it on that page
